### Get all accounts
GET http://localhost:8090/accounts

### Get account by id
GET http://localhost:8090/accounts/1

### Get non-existing account by id
GET http://localhost:8090/accounts/999

### Send POST request with json body
POST http://localhost:8090/accounts
Content-Type: application/json

{
  "ownerId": 0
}

### Send POST request with invalid data
POST http://localhost:8090/accounts
Content-Type: application/json

{
  "id": -1,
  "owner": "Ivo",
  "balance": -1111.0
}

### Send PUT request with json body
PUT http://localhost:8090/accounts/1
Content-Type: application/json

{
  "id": 1,
  "owner": "Ivo",
  "balance": 2222.0
}

### Send PUT with non-existing id
PUT http://localhost:8090/accounts/999
Content-Type: application/json

{
  "id": 999,
  "owner": "Ivo",
  "balance": 2222.0
}

### SEND PUT with invalid data
PUT http://localhost:8090/accounts/1
Content-Type: application/json

{
  "id": 1,
  "owner": "Ivo",
  "balance": -2222.0
}

### Send DELETE request
DELETE http://localhost:8080/accounts/1
