### Create a new transaction
POST http://localhost:8090/transactions
Content-Type: application/json

{
  "sourceAccountId": 2,
  "targetAccountId": 1,
  "amount": 30.0
}

### Create a new transaction with non-existing source account
POST http://localhost:8090/transactions
Content-Type: application/json

{
  "sourceAccountId": 999,
  "targetAccountId": 2,
  "amount": 30.0
}


### Create a new transaction with insufficient balance
POST http://localhost:8090/transactions
Content-Type: application/json

{
  "sourceAccountId": 1,
  "targetAccountId": 2,
  "amount": 99999.0
}

### Create a new transaction with negative amount
POST http://localhost:8090/transactions
Content-Type: application/json

{
  "sourceAccountId": 1,
  "targetAccountId": 2,
  "amount": -30.0
}
